run:
	# g++ -g 1012.cpp -std=c++17 --pedantic -o main
	# g++ -g 1997.cpp -std=c++17 --pedantic -o main
	# g++ -g 621.cpp -std=c++17 --pedantic -o main
	# g++ -g 2810.cpp -std=c++17 --pedantic -o main
	# g++ -g 1997.cpp -std=c++17 --pedantic -o main
	# g++ -g 621.cpp -std=c++17 --pedantic -o main
	# g++ -g 894.cpp -std=c++17 --pedantic -o main
	g++ -g 1883.cpp -std=c++17 --pedantic -o main
	./main
	# rm ./main
